import type { Metadata } from "next";

/** Absolute site root incl. GitHub Pages base path, e.g. https://user.github.io/kartu-site/ */
const origin = process.env.SITE_URL || "https://gypsypowerman-del.github.io";
const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
export const metadataBase = new URL(`${origin}${base}/`);

export const SITE_NAME = "KARTÚ";
export const SITE_DESCRIPTION = "A London-based interior design studio creating distinctive, thoughtful spaces for contemporary living.";

/** Share/canonical metadata for one page. `og` = file stem in /public/og (generated by scripts/og.mjs).
 *  Paths are relative (no leading slash) so Next joins them onto metadataBase incl. the base path. */
export function pageMeta({ path, og, title, description = SITE_DESCRIPTION }: { path: string; og: string; title?: string; description?: string }): Metadata {
  const shareTitle = title ? `${title} — ${SITE_NAME}` : `${SITE_NAME} — Interior Design Studio, London`;
  const image = { url: `og/${og}.jpg`, width: 1200, height: 630, alt: shareTitle };
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path.replace(/^\//, "") || "./" },
    openGraph: { type: "website", siteName: SITE_NAME, locale: "en_GB", url: path.replace(/^\//, "") || "./", title: shareTitle, description, images: [image] },
    twitter: { card: "summary_large_image", title: shareTitle, description, images: [image.url] },
  };
}
